name: 'jira-description-to-github-pr'
author: 'johnforeland'
description: 'Copy Jira descriptions to a Pull Request description'
branding:
  icon: "check-circle"
  color: "purple"
inputs:
  github-token:
    description: "Github access token"
    required: true
  jira-ticket-id:
    description: "Jira issue id"
    required: true
  jira-base-url: 
    description: "organization's jira url"
    required: true
  jira-token:
    description: "Jira token"
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'